module:
  mounts:
    - source: data
      target: data
    - source: templates
      target: layouts
outputFormats:
  apache_headers:
    baseName: .htaccess
    isPlainText: true
    mediatype: text/apache
    notAlternative: true
mediaTypes:
  text/apache:
    delimiter: ''
    suffixes: ['']
